sudo: required

language: python

services:
  - docker

env:
  matrix:
    - COMPILER_NAME=clang COMPILER_VERSION=3.8
    - COMPILER_NAME=clang COMPILER_VERSION=3.9
    - COMPILER_NAME=clang COMPILER_VERSION=4.0
    - COMPILER_NAME=clang COMPILER_VERSION=5.0
    - COMPILER_NAME=gcc COMPILER_VERSION=4.6
    - COMPILER_NAME=gcc COMPILER_VERSION=4.8
    - COMPILER_NAME=gcc COMPILER_VERSION=4.9
    - COMPILER_NAME=gcc COMPILER_VERSION=5.2
    - COMPILER_NAME=gcc COMPILER_VERSION=5.3
    - COMPILER_NAME=gcc COMPILER_VERSION=5.4
    - COMPILER_NAME=gcc COMPILER_VERSION=5.5
    - COMPILER_NAME=gcc COMPILER_VERSION=6.2
    - COMPILER_NAME=gcc COMPILER_VERSION=6.3
    - COMPILER_NAME=gcc COMPILER_VERSION=6.4
    - COMPILER_NAME=gcc COMPILER_VERSION=7.2

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo ${TRAVIS_PULL_REQUEST_BRANCH}; fi`
  - export BUILD_NUMBER=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "$TRAVIS_BUILD_NUMBER; else echo ""; fi`
  - python rebuild_and_upload.py --upload --tag ${TAG} --build_number ${BUILD_NUMBER} --${COMPILER_NAME} ${COMPILER_VERSION}
